-- Banco persistente do IPA – Construção de Temas
create table if not exists public.ipa_papers (
  id bigint generated by default as identity primary key,
  data date,
  tema text not null,
  comissoes jsonb not null default '[]'::jsonb,
  status text,
  origem text,
  fonte text,
  resumo text,
  posicoes_entidades text,
  encaminhamentos text,
  pontos_pendentes text,
  observacao_institucional text,
  mudancas text,
  assuntos_relacionados jsonb not null default '[]'::jsonb,
  comunicacao text,
  texto_original text not null,
  criado_em timestamptz not null default now()
);

create index if not exists ipa_papers_tema_idx on public.ipa_papers (tema);
create index if not exists ipa_papers_data_idx on public.ipa_papers (data desc);
create index if not exists ipa_papers_comissoes_gin_idx on public.ipa_papers using gin (comissoes);
create index if not exists ipa_papers_assuntos_gin_idx on public.ipa_papers using gin (assuntos_relacionados);
